- Penjualan : CRUD
- Ganti S : CRUD
- Pembelian 
	- Pelanggan : CRUD
	- Supplier : CRUD
- Cuci : CRUD
- Lebur : CRUD
- Baki : CRUD
- Keuangan 
	- Arus Kas			: CRUD
	- Hutang			: RUD
	- Piutang			: RUD
	- Operasional		: RUD
	- Biaya Pasti		: RUD
	- Pajak				: RUD
	- Gaji				: RUD
	- Nilai Stok		: RUD
	- Loss - Profit		: RUD
- Rekap
	- Item
		- per toko
		- per baki
		- per jenis emas
		- per sub-kategori
	- Pelanggan
		- Daftar transaksi jual-beli
	- Penjualan
		- per Sub Kategori
		- per Jenis Emas
		- per Tanggal
	- Pembelian 
		- Pelanggan
			- per Sub-Kategori
			- per Jenis Emas
			- per Tanggal
		- Supplier
			- per Sub-Kategori
			- per Jenis Emas
			- per Tanggal
	- Lebur
	- Cuci
	- Ganti S
	- Keuangan
		- Arus Kas
		- Hutang
		- Piutang
		- Operasional
		- Biaya Pasti
		- Pajak
		- Gaji
		- Nilai Stok
		- Loss - Profit
- Grafik
	- Penjualan 
	- Pembelian
	- Hutang
	- Piutang